# Detector mask files: allow for absolute paths  
data_directory: "run5_test"

poni_directory: "poni/"

poni_files:
  saxs: "atT_SAXS.poni"
  waxs: "atT_WAXS.poni"

mask_files:
  saxs: "RT_SAXS_mask.edf"
  waxs: "RT_WAXS_mask.edf"

# Detector dimensions (pixels) -- list
detector_shapes:
  saxs: [1043, 981]
  waxs: [195, 487]

compound: "C2H4"
file_format: ".raw"


read_data_function: null

# 1D Integration parameters
npt_radial: 1000  # Number of radial bins
error_model: "poisson"  # Error propagation model

# Experimental parameters (from Step1 notebook)
energy_keV: 12
density_g_cm3: 0.92
i0_offset: 0.0  # Set to 0 like in Step1 notebook
bstop_offset: 0.0  # Set to 0 like in Step1 notebook  
i0_air: 0.0  # Set to 0 like in Step1 notebook
bstop_air: 0.0  # Set to 0 like in Step1 notebook

# If thickness is null, compute it manually. Else, use thickness value
thickness: null

# TODO: implement extra functions if any are specified
# Empty list indicates no extra functions to add. 
extra_functions: []