data_directory: "/Users/vsomani/Documents/SWAXS_data_reduction_correction_Analysis/larger_test"
poni_directory: "poni"

poni_files:
  saxs: "atT_SAXS.poni"
  waxs: "atT_WAXS.poni"

mask_files:
  saxs: "RT_SAXS_mask_03.edf"
  waxs: "RT_WAXS_mask.edf"
# Detector dimensions (pixels) -- list
detector_shapes:
  saxs: [1043, 981]
  waxs: [195, 487]

compound: "C2H4"

# 1D Integration parameters
npt_radial: 1000  # Number of radial bins
error_model: "poisson"  # Error propagation model

# Experimental parameters (from Step1 notebook)
energy_keV: 12
density_g_cm3: 0.92
i0_offset: 0.0  
bstop_offset: 0.0 
i0_air: 0.0 
bstop_air: 0.0

# Options: 
# SWAXS -- perform both SAXS and WAXS
# SAXS -- SAXS only
# WAXS -- WAXS only
mode: "SWAXS"

# If thickness is null, compute it manually. Else, use thickness value
thickness: null

# Add mask


# TODO: implement data reading function if any are specified in utils.py
# Specify function name.
# IMPORTANT: Specified functions must be in utils.py and must follow input and output in exactly the same way as noted below

# INPUT: Raw data file path, output: dataframe of processed raw data in int32 and reshaped
# TODO: implement this
read_data_function: null


metadata_format: "csv"
# INPUT: raw data file path. Output: Tuple (i0, bstop, csv_dir). 
# XXX: Do we need other data from the metadata file? How would we use it, if so?
# Provide a different reading metadata function if not reading CSV or PDI
read_metadata_function: null
# TODO: implement extra functions if any are specified
extra_corrections: []
