data_directory: "/Users/vsomani/Documents/SWAXS_data_reduction_correction_Analysis/insitu_2025_BL15/refactor_pipeline_test"
# Poni directory should be within data directory
poni_directory: "poni"
poni_files:
  saxs: "atT_SAXS.poni"
  waxs: "atT_WAXS.poni"
# Null if you do not want to use mask correction
# Mask files are assumed to be in the PONI directory
mask_files:
  saxs: null
  waxs: null
# Detector dimensions (pixels). List formatted as [num rows, num columns]
detector_shapes:
  saxs: [1043, 981]
  waxs: [195, 487]
compound: "C2H4"
# 1D Integration parameters
npt_radial: 1000  # Number of radial bins
error_model: "poisson"  # Error propagation model
# Experimental parameters (from Step1 notebook)
energy_keV: 12
density_g_cm3: 0.92
i0_offset: 0.0  
bstop_offset: 0.0 
i0_air: 0.0 
bstop_air: 0.0
mode: "SWAXS" # Options: "SAXS", "WAXS", or "SWAXS" (both SAXS and WAXS)
metadata_format: "csv" # Options: "csv" or "pdi"
# If thickness is specified, use it. If null, compute it
thickness: null
# Below functions are used in place of existing functions.
# IMPORTANT: Make sure to specify function name and add function code in utils.py
# IMPORTANT: follow input and output in exactly the same way as noted below

# Impelement if not reading .raw
# INPUT: Raw data file path, OUTPUT: int32 reshaped dataframe of processed data
read_data_function: null 

# Provide a different reading metadata function if not reading CSV or PDI
# INPUT: raw data file path. Output: Tuple (i0, bstop, csv_dir). 
read_metadata_function: null
